kind: Deployment
apiVersion: v1
spec:
  state: RUNNING
  upgradeStrategy:
    kind: STATEFUL
  restoreStrategy:
    kind: LATEST_STATE
    allowNonRestoredState: false
  deploymentTargetId: DEPLOYMENTTARGETID
  template:
    spec:
      artifact:
        kind: JAR
        jarUri: JARURI
        flinkVersion: 1.9
        flinkImageRegistry: registry.platform.data-artisans.net/v2.0
        flinkImageRepository: flink
        flinkImageTag: 1.9.2-stream1-scala_2.12
      parallelism: 1
      resources:
        jobmanager:
          cpu: 0.5
          memory: 1G
        taskmanager:
          cpu: 1
          memory: 1G
      flinkConfiguration: {}
      logging:
        log4jLoggers: {}
